#![allow(unused_variables)]

use crate::{ConstraintsLayout, Field, TableKind, WitnessLayout};
use ark_ff::{AdditiveGroup as _, BigInteger as _};
use mavros_opcode_gen::interpreter;
use serde::{Deserialize, Serialize};

use crate::array::{BoxedLayout, BoxedValue, StructDescriptor};
use crate::interpreter::{Frame, Handler};

use crate::array::DataType;
use std::fmt::Display;
use std::ptr;

/// The number of u64 limbs making up a field element.
pub const FELT_LIMBS: usize = 4;

/// A user-facing source position attached to generated VM code.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceLocation {
    pub file: String,
    pub line: u64,
    pub column: u64,
}

impl SourceLocation {
    pub fn new(file: impl Into<String>, line: u64, column: u64) -> Self {
        Self {
            file: file.into(),
            line,
            column,
        }
    }
}

impl Display for SourceLocation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.file.starts_with('<') && self.file.ends_with('>') {
            write!(f, "{}", self.file)
        } else {
            write!(f, "{}:{}:{}", self.file, self.line, self.column)
        }
    }
}

/// One frame in a VM stack trace, ordered from the trapping frame to the entry point.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StackFrame {
    pub function: String,
    pub location: SourceLocation,
}

impl Display for StackFrame {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{} ({})", self.function, self.location)
    }
}

/// A compact, run-length encoded map from VM bytecode word offsets to Noir source locations.
///
/// This is serialized separately from the executable bytecode so production programs never pay
/// for source paths and locations. A location applies from its `code_offset` up to the next
/// location in the same function.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DebugInfo {
    pub format_version: u32,
    pub functions: Vec<DebugFunction>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DebugFunction {
    pub name: String,
    pub code_offset: usize,
    pub locations: Vec<DebugLocation>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DebugLocation {
    pub code_offset: usize,
    pub location: SourceLocation,
}

impl DebugInfo {
    /// Strip a common root from real source paths while preserving synthetic `<...>` locations.
    pub fn relativize_source_paths(&mut self, root: &std::path::Path) {
        for function in &mut self.functions {
            for location in &mut function.locations {
                let source = &mut location.location;
                if source.file.starts_with('<') && source.file.ends_with('>') {
                    continue;
                }
                if let Ok(relative) = std::path::Path::new(&source.file).strip_prefix(root) {
                    source.file = relative.to_string_lossy().into_owned();
                }
            }
        }
    }

    /// Resolve a word offset in the serialized program to its function and nearest source
    /// location. Callers can pass an address inside an opcode, not only its first word.
    pub fn stack_frame_at(&self, code_offset: usize) -> Option<StackFrame> {
        let function_index = self
            .functions
            .partition_point(|function| function.code_offset <= code_offset)
            .checked_sub(1)?;
        let function = &self.functions[function_index];
        let location_index = function
            .locations
            .partition_point(|location| location.code_offset <= code_offset)
            .checked_sub(1)?;

        Some(StackFrame {
            function: function.name.clone(),
            location: function.locations[location_index].location.clone(),
        })
    }
}

// ---------------------------------------------------------------------------
// Per-opcode profiling (enabled with the `vm-profile` feature).
//
// The counters live in `VM::opcode_profile` (see below) rather than in a global
// static: the dispatch loop holds a unique `&mut VM`, so plain `u64` adds with
// no atomics suffice. Each generated handler reads the cycle counter at
// entry/exit and accumulates `(count, cycles)` into that buffer, indexed by
// opcode discriminant. `OPCODE_NAMES` (generated by the macro) labels the rows;
// `read_cycles` is the timer source; `VM::report_opcode_profile` prints them.
// ---------------------------------------------------------------------------

/// Read the architectural cycle counter. Cheap, monotonic, userspace-readable.
#[cfg(feature = "vm-profile")]
#[inline(always)]
pub fn read_cycles() -> u64 {
    #[cfg(target_arch = "aarch64")]
    {
        let v: u64;
        // Virtual count register; readable from EL0 on Linux/macOS.
        unsafe { core::arch::asm!("mrs {}, cntvct_el0", out(reg) v, options(nomem, nostack)) };
        v
    }
    #[cfg(target_arch = "x86_64")]
    {
        unsafe { core::arch::x86_64::_rdtsc() }
    }
    #[cfg(not(any(target_arch = "aarch64", target_arch = "x86_64")))]
    {
        0
    }
}

/// Frequency of the counter read by [`read_cycles`], in Hz, for converting the
/// accumulated counts into wall-clock time.
#[cfg(all(feature = "vm-profile", target_arch = "aarch64"))]
fn cycle_freq_hz() -> u64 {
    let v: u64;
    unsafe { core::arch::asm!("mrs {}, cntfrq_el0", out(reg) v, options(nomem, nostack)) };
    v
}

#[cfg(feature = "vm-profile")]
impl VM {
    /// Print this VM's per-opcode profiling report to stderr, sorted by
    /// accumulated cycles.
    pub fn report_opcode_profile(&self, label: &str) {
        let mut rows: Vec<(&str, u64, u64)> = OPCODE_NAMES
            .iter()
            .zip(self.opcode_profile.iter())
            .map(|(name, &(count, cycles))| (*name, count, cycles))
            .filter(|(_, count, _)| *count > 0)
            .collect();

        let total_count: u64 = rows.iter().map(|(_, c, _)| *c).sum();
        let total_cycles: u64 = rows.iter().map(|(_, _, cy)| *cy).sum();

        rows.sort_by(|a, b| b.2.cmp(&a.2));

        #[cfg(target_arch = "aarch64")]
        let freq = cycle_freq_hz();
        #[cfg(not(target_arch = "aarch64"))]
        let freq = 0u64;

        eprintln!("\n=== VM opcode profile: {label} ===");
        eprintln!(
            "total opcodes executed: {total_count}   total counter ticks: {total_cycles}{}",
            if freq > 0 {
                format!(
                    "   (~{:.3} ms @ {} Hz)",
                    (total_cycles as f64 / freq as f64) * 1e3,
                    freq
                )
            } else {
                String::new()
            }
        );
        eprintln!(
            "{:<22} {:>14} {:>7} {:>16} {:>7} {:>10}",
            "opcode", "count", "count%", "ticks", "tick%", "ticks/op"
        );
        for (name, count, cycles) in &rows {
            eprintln!(
                "{:<22} {:>14} {:>6.2}% {:>16} {:>6.2}% {:>10.1}",
                name,
                count,
                100.0 * *count as f64 / total_count.max(1) as f64,
                cycles,
                100.0 * *cycles as f64 / total_cycles.max(1) as f64,
                *cycles as f64 / (*count).max(1) as f64,
            );
        }
        eprintln!("=== end profile: {label} ===\n");
    }
}

/// Element storage kind for array lookup opcodes.
/// Encoded as usize for compatibility with the opcode proc macro.
pub const ELEM_WORD: usize = 0;
pub const ELEM_FIELD: usize = 1;
pub const ELEM_WITNESS: usize = 2;

/// Read an array element as a Field and bump out_db accordingly.
#[inline(always)]
unsafe fn lookup_elem_bump_db(ptr: *mut u64, elem_kind: usize, coeff: Field, vm: &mut VM) {
    match elem_kind {
        ELEM_WORD => unsafe {
            let v = Field::from(*(ptr as *const u64));
            *vm.data.as_ad.out_db += coeff * v;
        },
        ELEM_FIELD => unsafe {
            let v = *(ptr as *const Field);
            *vm.data.as_ad.out_db += coeff * v;
        },
        ELEM_WITNESS => {
            let elem = BoxedValue(unsafe { *(ptr as *const *mut u64) });
            elem.bump_db(coeff, vm);
        }
        _ => unreachable!(),
    }
}

/// Read a pure (non-WitnessOf) array element as a Field value.
#[inline(always)]
unsafe fn read_pure_elem_as_field(ptr: *mut u64, elem_kind: usize) -> Field {
    match elem_kind {
        ELEM_WORD => Field::from(unsafe { *(ptr as *const u64) }),
        ELEM_FIELD => unsafe { *(ptr as *const Field) },
        _ => unreachable!(),
    }
}

#[inline(always)]
fn int_mask(bits: u64) -> u128 {
    if bits >= 128 {
        u128::MAX
    } else {
        (1u128 << bits) - 1
    }
}

#[repr(C)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct U128 {
    pub lo: u64,
    pub hi: u64,
}

const _: () = assert!(
    std::mem::size_of::<U128>() == 2 * std::mem::size_of::<u64>()
        && std::mem::align_of::<U128>() == std::mem::align_of::<u64>(),
    "U128 must have the same cell layout as two u64 words"
);

impl U128 {
    #[inline(always)]
    pub fn from_u128(value: u128) -> Self {
        Self {
            lo: value as u64,
            hi: (value >> 64) as u64,
        }
    }

    #[inline(always)]
    pub fn to_u128(self) -> u128 {
        (self.lo as u128) | ((self.hi as u128) << 64)
    }

    #[inline(always)]
    pub fn wrapping_add(self, rhs: Self) -> Self {
        Self::from_u128(self.to_u128().wrapping_add(rhs.to_u128()))
    }

    #[inline(always)]
    pub fn wrapping_sub(self, rhs: Self) -> Self {
        Self::from_u128(self.to_u128().wrapping_sub(rhs.to_u128()))
    }

    #[inline(always)]
    pub fn wrapping_mul(self, rhs: Self) -> Self {
        Self::from_u128(self.to_u128().wrapping_mul(rhs.to_u128()))
    }

    #[inline(always)]
    pub fn wrapping_shl(self, rhs: u32) -> Self {
        Self::from_u128(self.to_u128().wrapping_shl(rhs))
    }

    #[inline(always)]
    pub fn wrapping_shr(self, rhs: u32) -> Self {
        Self::from_u128(self.to_u128().wrapping_shr(rhs))
    }

    #[inline(always)]
    pub fn truncate(self, bits: u64) -> Self {
        Self::from_u128(self.to_u128() & int_mask(bits))
    }
}

impl Ord for U128 {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.hi.cmp(&other.hi).then(self.lo.cmp(&other.lo))
    }
}

impl PartialOrd for U128 {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl std::ops::Div for U128 {
    type Output = Self;

    fn div(self, rhs: Self) -> Self::Output {
        Self::from_u128(self.to_u128() / rhs.to_u128())
    }
}

impl std::ops::Rem for U128 {
    type Output = Self;

    fn rem(self, rhs: Self) -> Self::Output {
        Self::from_u128(self.to_u128() % rhs.to_u128())
    }
}

impl std::ops::BitAnd for U128 {
    type Output = Self;

    fn bitand(self, rhs: Self) -> Self::Output {
        Self {
            lo: self.lo & rhs.lo,
            hi: self.hi & rhs.hi,
        }
    }
}

impl std::ops::BitOr for U128 {
    type Output = Self;

    fn bitor(self, rhs: Self) -> Self::Output {
        Self {
            lo: self.lo | rhs.lo,
            hi: self.hi | rhs.hi,
        }
    }
}

impl std::ops::BitXor for U128 {
    type Output = Self;

    fn bitxor(self, rhs: Self) -> Self::Output {
        Self {
            lo: self.lo ^ rhs.lo,
            hi: self.hi ^ rhs.hi,
        }
    }
}

impl std::ops::Not for U128 {
    type Output = Self;

    fn not(self) -> Self::Output {
        Self {
            lo: !self.lo,
            hi: !self.hi,
        }
    }
}

unsafe fn for_each_array_leaf<F: FnMut(usize, *mut u64)>(
    array: BoxedValue,
    stride: usize,
    mut f: F,
) -> usize {
    unsafe fn go<F: FnMut(usize, *mut u64)>(
        array: BoxedValue,
        stride: usize,
        f: &mut F,
        idx: &mut usize,
    ) {
        let layout = array.layout();
        if layout.is_boxed_array() {
            let size = layout.array_size();
            for i in 0..size {
                let cell_ptr = array.array_idx(i, 1);
                let inner = unsafe { *(cell_ptr as *mut BoxedValue) };
                let inner_layout = inner.layout();
                if inner_layout.is_boxed_array() || inner_layout.is_prim_array() {
                    unsafe { go(inner, stride, f, idx) };
                } else {
                    f(*idx, cell_ptr);
                    *idx += 1;
                }
            }
        } else if layout.is_prim_array() {
            let n_elems = layout.array_size() / stride;
            for i in 0..n_elems {
                f(*idx, array.array_idx(i, stride));
                *idx += 1;
            }
        } else {
            panic!(
                "Unexpected array data type in lookup-table flatten: {:?}",
                layout.data_type()
            );
        }
    }
    let mut idx = 0;
    unsafe { go(array, stride, &mut f, &mut idx) };
    idx
}

#[derive(Clone, Copy)]
pub struct FramePosition(pub usize);

impl FramePosition {
    pub fn offset(&self, offset: isize) -> FramePosition {
        FramePosition(self.0.checked_add_signed(offset).unwrap())
    }
    pub fn return_data_ptr() -> FramePosition {
        FramePosition(0)
    }
    pub fn return_address_ptr() -> FramePosition {
        FramePosition(1)
    }
}

pub struct JumpTarget(pub isize);

#[derive(Clone)]
pub enum AllocationType {
    Stack,
    Heap,
}

#[derive(Clone)]
pub enum AlocationEvent {
    Alloc(AllocationType, usize),
    Free(AllocationType, usize),
}

#[derive(Clone)]
pub struct AllocationInstrumenter {
    pub events: Vec<AlocationEvent>,
}

impl AllocationInstrumenter {
    pub fn new() -> Self {
        Self { events: vec![] }
    }

    pub fn alloc(&mut self, ty: AllocationType, size: usize) {
        self.events.push(AlocationEvent::Alloc(ty, size));
    }

    pub fn free(&mut self, ty: AllocationType, size: usize) {
        self.events.push(AlocationEvent::Free(ty, size));
    }

    /// Returns the final memory usage in bytes (0 means no leak).
    pub fn final_memory_usage(&self) -> usize {
        let mut current_stack = 0usize;
        let mut current_heap = 0usize;

        for event in &self.events {
            match event {
                AlocationEvent::Alloc(AllocationType::Stack, size) => {
                    current_stack += size * 8;
                }
                AlocationEvent::Alloc(AllocationType::Heap, size) => {
                    current_heap += size * 8;
                }
                AlocationEvent::Free(AllocationType::Stack, size) => {
                    current_stack = current_stack.saturating_sub(*size * 8);
                }
                AlocationEvent::Free(AllocationType::Heap, size) => {
                    current_heap = current_heap.saturating_sub(*size * 8);
                }
            }
        }

        current_stack + current_heap
    }
}

#[derive(Clone)]
pub struct TableInfo {
    pub multiplicities_wit: *mut Field,
    pub num_indices: usize,
    pub kind: TableKind,
    pub length: usize,
    pub elem_inverses_witness_section_offset: usize,
    pub elem_inverses_constraint_section_offset: usize,
}

#[derive(Copy, Clone)]
pub struct FwdArrays {
    pub out_a: *mut Field,
    pub out_b: *mut Field,
    pub out_c: *mut Field,
    pub out_a_base: *mut Field,
    pub algebraic_witness: *mut Field,
    pub multiplicities_witness: *mut Field,
    pub lookups_a: *mut Field,
    pub lookups_b: *mut Field,
    pub lookups_c: *mut Field,
    pub elem_inverses_constraint_section_offset: usize,
    pub elem_inverses_witness_section_offset: usize,
}

#[derive(Copy, Clone)]
pub struct AdArrays {
    pub out_da: *mut Field,
    pub out_db: *mut Field,
    pub out_dc: *mut Field,
    pub ad_coeffs: *const Field,
    pub current_wit_off: usize,
    pub logup_wit_challenge_off: usize,
    pub current_wit_multiplicities_off: usize,
    pub current_wit_tables_off: usize,
    pub current_wit_lookups_off: usize,
    pub current_cnst_off: usize,
    pub current_cnst_tables_off: usize,
    pub current_cnst_lookups_off: usize,
}

pub union Arrays {
    pub as_forward: FwdArrays,
    pub as_ad: AdArrays,
}

/// Number of slots in the fixed-size table caches ([`VM::rgchk_tables`]/[`VM::spread_tables`]).
/// These are indexed by table size in bits, so this covers every width in `0..=32`.
pub const NUM_TABLE_SIZE_SLOTS: usize = 33;

pub struct VM {
    pub data: Arrays,
    pub allocation_instrumenter: AllocationInstrumenter,
    pub tables: Vec<TableInfo>,
    /// Lazily-allocated rangecheck tables, indexed by table size in bits (a `2^bits`-row table).
    pub rgchk_tables: [Option<usize>; NUM_TABLE_SIZE_SLOTS],
    pub spread_tables: [Option<usize>; NUM_TABLE_SIZE_SLOTS],
    pub globals: *mut u64,
    pub struct_layouts: Vec<StructDescriptor>,
    /// Interned constant pool (flat words), read by the `mov_const_pool` opcode.
    pub constants: Vec<u64>,
    /// Set when the program executes a trap (e.g. a failed assertion). The
    /// interpreter checks this after dispatch returns to distinguish a clean
    /// halt from a trapped one.
    pub trapped: bool,
    program_base: *const u64,
    program_len: usize,
    debug_info: DebugInfo,
    pub(crate) stack_trace: Vec<StackFrame>,
    /// Per-opcode `(invocation_count, accumulated_cycles)`, indexed by opcode
    /// discriminant. Written by the generated handlers; only present under the
    /// `vm-profile` feature.
    #[cfg(feature = "vm-profile")]
    pub opcode_profile: Vec<(u64, u64)>,
}

impl VM {
    pub fn new_witgen(
        out_a: *mut Field,
        out_b: *mut Field,
        out_c: *mut Field,
        algebraic_witness: *mut Field,
        multiplicities_witness: *mut Field,
        lookups_a: *mut Field,
        lookups_b: *mut Field,
        lookups_c: *mut Field,
        elem_inverses_constraint_section_offset: usize,
        elem_inverses_witness_section_offset: usize,
        globals: *mut u64,
        struct_layouts: Vec<StructDescriptor>,
        constants: Vec<u64>,
    ) -> Self {
        Self {
            data: Arrays {
                as_forward: FwdArrays {
                    out_a,
                    out_b,
                    out_c,
                    out_a_base: out_a,
                    algebraic_witness,
                    multiplicities_witness,
                    lookups_b,
                    lookups_a,
                    lookups_c,
                    elem_inverses_constraint_section_offset,
                    elem_inverses_witness_section_offset,
                },
            },
            allocation_instrumenter: AllocationInstrumenter::new(),
            tables: vec![],
            rgchk_tables: [None; NUM_TABLE_SIZE_SLOTS],
            spread_tables: [None; NUM_TABLE_SIZE_SLOTS],
            globals,
            struct_layouts,
            constants,
            trapped: false,
            program_base: ptr::null(),
            program_len: 0,
            debug_info: DebugInfo::default(),
            stack_trace: Vec::new(),
            #[cfg(feature = "vm-profile")]
            opcode_profile: vec![(0, 0); NUM_OPCODES],
        }
    }

    pub fn new_ad(
        out_da: *mut Field,
        out_db: *mut Field,
        out_dc: *mut Field,
        ad_coeffs: *const Field,

        witness_layout: WitnessLayout,
        constraints_layout: ConstraintsLayout,
        globals: *mut u64,
        struct_layouts: Vec<StructDescriptor>,
        constants: Vec<u64>,
    ) -> Self {
        Self {
            data: Arrays {
                as_ad: AdArrays {
                    out_da,
                    out_db,
                    out_dc,
                    ad_coeffs,
                    current_wit_off: 0,
                    logup_wit_challenge_off: witness_layout.challenges_start(),
                    current_wit_multiplicities_off: witness_layout.multiplicities_start(),
                    current_wit_tables_off: witness_layout.tables_data_start(),
                    current_wit_lookups_off: witness_layout.lookups_data_start(),
                    current_cnst_off: 0,
                    current_cnst_tables_off: constraints_layout.tables_data_start(),
                    current_cnst_lookups_off: constraints_layout.lookups_data_start(),
                },
            },
            allocation_instrumenter: AllocationInstrumenter::new(),
            tables: vec![],
            rgchk_tables: [None; NUM_TABLE_SIZE_SLOTS],
            spread_tables: [None; NUM_TABLE_SIZE_SLOTS],
            globals,
            struct_layouts,
            constants,
            trapped: false,
            program_base: ptr::null(),
            program_len: 0,
            debug_info: DebugInfo::default(),
            stack_trace: Vec::new(),
            #[cfg(feature = "vm-profile")]
            opcode_profile: vec![(0, 0); NUM_OPCODES],
        }
    }

    pub fn set_debug_context(
        &mut self,
        program_base: *const u64,
        program_len: usize,
        debug_info: DebugInfo,
    ) {
        self.program_base = program_base;
        self.program_len = program_len;
        self.debug_info = debug_info;
    }

    fn program_offset(&self, pc: *const u64) -> Option<usize> {
        if self.program_base.is_null() {
            return None;
        }
        let offset = unsafe { pc.offset_from(self.program_base) };
        (offset >= 0 && (offset as usize) < self.program_len).then_some(offset as usize)
    }

    pub fn capture_trap(&mut self, pc: *const u64, frame: Frame) {
        self.trapped = true;
        self.stack_trace.clear();

        let Some(offset) = self.program_offset(pc) else {
            return;
        };
        if let Some(frame) = self.debug_info.stack_frame_at(offset) {
            self.stack_trace.push(frame);
        }

        let mut current = frame;
        while !current.data.is_null() {
            let parent_data = unsafe { *current.data.offset(-1) as *mut u64 };
            if parent_data.is_null() {
                break;
            }

            let return_pc = unsafe { *current.data.offset(1) as *const u64 };
            if let Some(return_offset) = self.program_offset(return_pc)
                && let Some(frame) = self
                    .debug_info
                    .stack_frame_at(return_offset.saturating_sub(1))
            {
                self.stack_trace.push(frame);
            }
            current = Frame { data: parent_data };
        }
    }
}

/// Compute spread of a u32: interleave zero bits between each bit.
pub(crate) fn spread_bits(v: u32) -> u64 {
    let mut x = v as u64;
    x = (x | (x << 16)) & 0x0000_FFFF_0000_FFFF;
    x = (x | (x << 8)) & 0x00FF_00FF_00FF_00FF;
    x = (x | (x << 4)) & 0x0F0F_0F0F_0F0F_0F0F;
    x = (x | (x << 2)) & 0x3333_3333_3333_3333;
    x = (x | (x << 1)) & 0x5555_5555_5555_5555;
    x
}

/// Compact even-positioned bits into contiguous low bits.
fn compact_bits(mut x: u64) -> u32 {
    x &= 0x5555_5555_5555_5555;
    x = (x | (x >> 1)) & 0x3333_3333_3333_3333;
    x = (x | (x >> 2)) & 0x0F0F_0F0F_0F0F_0F0F;
    x = (x | (x >> 4)) & 0x00FF_00FF_00FF_00FF;
    x = (x | (x >> 8)) & 0x0000_FFFF_0000_FFFF;
    x = (x | (x >> 16)) & 0x0000_0000_FFFF_FFFF;
    x as u32
}

/// Extract even bits and odd bits from a spread sum. Returns (odd_bits, even_bits).
fn unspread_bits(v: u64) -> (u32, u32) {
    let even = compact_bits(v);
    let odd = compact_bits(v >> 1);
    (odd, even)
}

/// Emit a forward key-value lookup: bump multiplicity and write 2 lookup tape entries.
unsafe fn forward_kv_lookup_emit(
    table_idx: usize,
    key: Field,
    result: Field,
    flag_u64: u64,
    vm: &mut VM,
) {
    let table_info = &vm.tables[table_idx];

    // Entry 1 (x-constraint): table_id, result_value, 0
    unsafe {
        *(vm.data.as_forward.lookups_a as *mut u64) = table_idx as u64;
        *vm.data.as_forward.lookups_b = result;
        *(vm.data.as_forward.lookups_c as *mut u64) = 0;
        vm.data.as_forward.lookups_a = vm.data.as_forward.lookups_a.offset(1);
        vm.data.as_forward.lookups_b = vm.data.as_forward.lookups_b.offset(1);
        vm.data.as_forward.lookups_c = vm.data.as_forward.lookups_c.offset(1);
    }

    // Entry 2 (y-constraint): table_id, key, flag
    unsafe {
        *(vm.data.as_forward.lookups_a as *mut u64) = table_idx as u64;
        if flag_u64 != 0 {
            let key_u64 = ark_ff::PrimeField::into_bigint(key).0[0];
            let ptr = table_info.multiplicities_wit.offset(key_u64 as isize);
            *(ptr as *mut u64) += flag_u64;
            *(vm.data.as_forward.lookups_b as *mut u64) = key_u64;
        } else {
            *(vm.data.as_forward.lookups_b as *mut Field) = key;
        }
        *(vm.data.as_forward.lookups_c as *mut u64) = flag_u64;
        vm.data.as_forward.lookups_a = vm.data.as_forward.lookups_a.offset(1);
        vm.data.as_forward.lookups_b = vm.data.as_forward.lookups_b.offset(1);
        vm.data.as_forward.lookups_c = vm.data.as_forward.lookups_c.offset(1);
    }
}

/// Emit AD bumps for a key-value lookup (x-constraint + y-constraint + sum).
unsafe fn ad_kv_lookup_emit(
    table_idx: usize,
    key: BoxedValue,
    result: BoxedValue,
    flag: BoxedValue,
    vm: &mut VM,
) {
    let table_info = &vm.tables[table_idx];
    let cnst_off = table_info.elem_inverses_constraint_section_offset;
    let length = table_info.length;
    // Sum constraint sits past the table's per-entry constraints: spread tables
    // fold each entry into one constraint, arrays use two. Rangecheck tables
    // are key-only and never reach this key-value lookup path.
    let sum_off = match table_info.kind {
        TableKind::Spread => cnst_off + length,
        TableKind::Array => cnst_off + 2 * length,
        TableKind::RangeCheck => panic!("ad_kv_lookup_emit called on a rangecheck table"),
    };

    let x_coeff = unsafe {
        let r = *vm
            .data
            .as_ad
            .ad_coeffs
            .add(vm.data.as_ad.current_cnst_lookups_off);
        vm.data.as_ad.current_cnst_lookups_off += 1;
        r
    };
    let x_wit_off = unsafe {
        let r = vm.data.as_ad.current_wit_lookups_off;
        vm.data.as_ad.current_wit_lookups_off += 1;
        r
    };
    let y_coeff = unsafe {
        let r = *vm
            .data
            .as_ad
            .ad_coeffs
            .add(vm.data.as_ad.current_cnst_lookups_off);
        vm.data.as_ad.current_cnst_lookups_off += 1;
        r
    };
    let y_wit_off = unsafe {
        let r = vm.data.as_ad.current_wit_lookups_off;
        vm.data.as_ad.current_wit_lookups_off += 1;
        r
    };
    let inv_sum_coeff = unsafe { *vm.data.as_ad.ad_coeffs.add(sum_off) };

    // x-constraint: beta * result - x_lookup = 0
    unsafe {
        *vm.data
            .as_ad
            .out_da
            .add(vm.data.as_ad.logup_wit_challenge_off + 1) += x_coeff;
    }
    result.bump_db(x_coeff, vm);
    unsafe {
        *vm.data.as_ad.out_dc.add(x_wit_off) -= x_coeff;
    }

    // y-constraint: y * (alpha - x_lookup - key) = flag
    unsafe {
        *vm.data.as_ad.out_da.add(y_wit_off) += y_coeff;
        *vm.data
            .as_ad
            .out_db
            .add(vm.data.as_ad.logup_wit_challenge_off) += y_coeff;
        *vm.data.as_ad.out_db.add(x_wit_off) -= y_coeff;
    }
    key.bump_db(-y_coeff, vm);
    flag.bump_dc(y_coeff, vm);

    // Sum constraint
    unsafe {
        *vm.data.as_ad.out_dc.add(y_wit_off) += inv_sum_coeff;
    }
}

#[interpreter]
mod def {
    #[raw_opcode]
    fn jmp(pc: *const u64, frame: Frame, vm: &mut VM, target: JumpTarget) -> (*const u64, Frame) {
        let pc = unsafe { pc.offset(target.0) };
        (pc, frame)
    }

    #[raw_opcode]
    fn jmp_if(
        pc: *const u64,
        frame: Frame,
        vm: &mut VM,
        #[frame] cond: u64,
        if_t: JumpTarget,
        if_f: JumpTarget,
    ) -> (*const u64, Frame) {
        let target = if cond != 0 { if_t } else { if_f };
        let pc = unsafe { pc.offset(target.0) };
        (pc, frame)
    }

    #[raw_opcode]
    fn call(
        pc: *const u64,
        frame: Frame,
        vm: &mut VM,
        func: JumpTarget,
        args: &[(usize, FramePosition)],
        ret: FramePosition,
    ) -> (*const u64, Frame) {
        let func_pc = unsafe { pc.offset(func.0) };
        let func_frame_size = unsafe { *func_pc.offset(-1) };
        let new_frame = Frame::push(func_frame_size, frame, vm);
        let ret_data_ptr = unsafe { frame.data.add(ret.0) };
        let ret_pc = unsafe { pc.offset(4 + 2 * args.len() as isize) };

        unsafe {
            *new_frame.data = ret_data_ptr as u64;
            *new_frame.data.offset(1) = ret_pc as u64;
        };

        let mut current_child = unsafe { new_frame.data.offset(2) };

        for (arg_size, arg_pos) in args {
            unsafe { frame.write_to(current_child, arg_pos.0 as isize, *arg_size) };
            current_child = unsafe { current_child.add(*arg_size) };
        }

        (func_pc, new_frame)
    }

    #[raw_opcode]
    fn ret(_pc: *const u64, frame: Frame, vm: &mut VM) -> (*const u64, Frame) {
        let ret_address = unsafe { *frame.data.offset(1) } as *mut u64;
        let new_frame = frame.pop(vm);
        if new_frame.data.is_null() {
            // Halt: returning a null pc tells `dispatch` to stop.
            return (std::ptr::null(), new_frame);
        }
        (ret_address, new_frame)
    }

    /// Halts execution and marks the VM as trapped. The interpreter analogue
    /// of the WASM target's `unreachable`: the assert-family opcodes delegate
    /// here when their check fails.
    #[raw_opcode]
    fn trap(pc: *const u64, frame: Frame, vm: &mut VM) -> (*const u64, Frame) {
        vm.capture_trap(pc, frame);
        (std::ptr::null(), frame)
    }

    #[raw_opcode]
    fn r1c(
        pc: *const u64,
        frame: Frame,
        vm: &mut VM,
        #[frame] a: Field,
        #[frame] b: Field,
        #[frame] c: Field,
    ) -> (*const u64, Frame) {
        unsafe {
            *vm.data.as_forward.out_a = a;
            *vm.data.as_forward.out_b = b;
            *vm.data.as_forward.out_c = c;
        }

        unsafe {
            vm.data.as_forward.out_a = vm.data.as_forward.out_a.offset(1);
            vm.data.as_forward.out_b = vm.data.as_forward.out_b.offset(1);
            vm.data.as_forward.out_c = vm.data.as_forward.out_c.offset(1);
        };
        let pc = unsafe { pc.offset(4) };
        (pc, frame)
    }

    #[raw_opcode]
    fn write_witness(
        pc: *const u64,
        frame: Frame,
        vm: &mut VM,
        #[frame] val: Field,
    ) -> (*const u64, Frame) {
        unsafe {
            *vm.data.as_forward.algebraic_witness = val;
            vm.data.as_forward.algebraic_witness = vm.data.as_forward.algebraic_witness.offset(1);
        };
        let pc = unsafe { pc.offset(2) };
        (pc, frame)
    }

    #[opcode]
    fn nop() {}

    #[opcode]
    fn mov_const(#[out] res: *mut u64, val: u64) {
        unsafe {
            *res = val;
        }
    }

    #[opcode]
    fn mov_frame(frame: Frame, target: FramePosition, source: FramePosition, size: usize) {
        frame.memcpy(target.0 as isize, source.0 as isize, size);
    }

    #[opcode]
    fn write_ptr(
        frame: Frame,
        #[frame] ptr: *mut u64,
        offset: isize,
        src: FramePosition,
        size: usize,
    ) {
        let ptr = unsafe { ptr.offset(offset) };
        unsafe { frame.write_to(ptr, src.0 as isize, size) };
    }

    #[opcode]
    fn add_int(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64, bits: u64) {
        unsafe {
            let sum = a.wrapping_add(b);
            *res = if bits >= 64 {
                sum
            } else {
                sum & ((1u64 << bits) - 1)
            };
        }
    }

    #[opcode]
    fn sub_int(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64, bits: u64) {
        unsafe {
            let diff = a.wrapping_sub(b);
            *res = if bits >= 64 {
                diff
            } else {
                diff & ((1u64 << bits) - 1)
            };
        }
    }

    #[opcode]
    fn mul_int(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64, bits: u64) {
        unsafe {
            let prod = a.wrapping_mul(b);
            *res = if bits >= 64 {
                prod
            } else {
                prod & ((1u64 << bits) - 1)
            };
        }
    }

    #[opcode]
    fn add_u128(#[out] res: *mut U128, #[frame] a: U128, #[frame] b: U128) {
        unsafe { *res = a.wrapping_add(b) };
    }

    #[opcode]
    fn sub_u128(#[out] res: *mut U128, #[frame] a: U128, #[frame] b: U128) {
        unsafe { *res = a.wrapping_sub(b) };
    }

    #[opcode]
    fn mul_u128(#[out] res: *mut U128, #[frame] a: U128, #[frame] b: U128) {
        unsafe { *res = a.wrapping_mul(b) };
    }

    #[opcode]
    fn div_u64(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64) {
        unsafe {
            *res = a / b;
        }
    }

    #[opcode]
    fn mod_u64(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64) {
        unsafe {
            *res = a % b;
        }
    }

    #[opcode]
    fn div_s64(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64, bits: u64) {
        unsafe {
            let shift = 64 - bits;
            let a = ((a << shift) as i64) >> shift;
            let b = ((b << shift) as i64) >> shift;
            *res = (a / b) as u64
                & if bits >= 64 {
                    u64::MAX
                } else {
                    (1u64 << bits) - 1
                };
        }
    }

    #[opcode]
    fn mod_s64(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64, bits: u64) {
        unsafe {
            let shift = 64 - bits;
            let a = ((a << shift) as i64) >> shift;
            let b = ((b << shift) as i64) >> shift;
            *res = (a % b) as u64
                & if bits >= 64 {
                    u64::MAX
                } else {
                    (1u64 << bits) - 1
                };
        }
    }

    #[opcode]
    fn div_u128(#[out] res: *mut U128, #[frame] a: U128, #[frame] b: U128) {
        unsafe { *res = a / b };
    }

    #[opcode]
    fn mod_u128(#[out] res: *mut U128, #[frame] a: U128, #[frame] b: U128) {
        unsafe { *res = a % b };
    }

    #[opcode]
    fn and_u64(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64) {
        unsafe {
            *res = a & b;
        }
    }

    #[opcode]
    fn or_u64(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64) {
        unsafe {
            *res = a | b;
        }
    }

    #[opcode]
    fn xor_u64(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64) {
        unsafe {
            *res = a ^ b;
        }
    }

    #[opcode]
    fn and_u128(#[out] res: *mut U128, #[frame] a: U128, #[frame] b: U128) {
        unsafe { *res = a & b };
    }

    #[opcode]
    fn or_u128(#[out] res: *mut U128, #[frame] a: U128, #[frame] b: U128) {
        unsafe { *res = a | b };
    }

    #[opcode]
    fn xor_u128(#[out] res: *mut U128, #[frame] a: U128, #[frame] b: U128) {
        unsafe { *res = a ^ b };
    }

    #[opcode]
    fn shl_u64(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64, bits: u64) {
        unsafe {
            let shifted = a << b;
            *res = if bits >= 64 {
                shifted
            } else {
                shifted & ((1u64 << bits) - 1)
            };
        }
    }

    #[opcode]
    fn ushr_u64(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64) {
        unsafe {
            *res = a >> b;
        }
    }

    #[opcode]
    fn shl_u128(#[out] res: *mut U128, #[frame] a: U128, #[frame] b: U128) {
        unsafe { *res = a.wrapping_shl(b.lo as u32) };
    }

    #[opcode]
    fn ushr_u128(#[out] res: *mut U128, #[frame] a: U128, #[frame] b: U128) {
        unsafe { *res = a.wrapping_shr(b.lo as u32) };
    }

    #[opcode]
    fn not_u64(#[out] res: *mut u64, #[frame] a: u64) {
        unsafe {
            *res = !a;
        }
    }

    #[opcode]
    fn not_u128(#[out] res: *mut U128, #[frame] a: U128) {
        unsafe { *res = !a };
    }

    #[opcode]
    fn eq_u64(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64) {
        unsafe {
            *res = (a == b) as u64;
        }
    }

    #[opcode]
    fn lt_u64(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64) {
        unsafe {
            *res = (a < b) as u64;
        }
    }

    #[opcode]
    fn eq_u128(#[out] res: *mut u64, #[frame] a: U128, #[frame] b: U128) {
        unsafe {
            *res = (a == b) as u64;
        }
    }

    #[opcode]
    fn field_eq(#[out] res: *mut u64, #[frame] a: Field, #[frame] b: Field) {
        unsafe {
            *res = (a == b) as u64;
        }
    }

    #[opcode]
    fn lt_field(#[out] res: *mut u64, #[frame] a: Field, #[frame] b: Field) {
        unsafe {
            *res = (ark_ff::PrimeField::into_bigint(a) < ark_ff::PrimeField::into_bigint(b)) as u64;
        }
    }

    #[opcode]
    fn lt_u128(#[out] res: *mut u64, #[frame] a: U128, #[frame] b: U128) {
        unsafe {
            *res = (a < b) as u64;
        }
    }

    #[opcode]
    fn lt_s64(#[out] res: *mut u64, #[frame] a: u64, #[frame] b: u64, bits: u64) {
        unsafe {
            let shift = 64 - bits;
            let a = ((a << shift) as i64) >> shift;
            let b = ((b << shift) as i64) >> shift;
            *res = (a < b) as u64;
        }
    }

    #[opcode]
    fn truncate_u64(#[out] res: *mut u64, #[frame] a: u64, to_bits: u64) {
        unsafe {
            let mask = if to_bits >= 64 {
                u64::MAX
            } else {
                (1u64 << to_bits) - 1
            };
            *res = a & mask;
        }
    }

    #[opcode]
    fn truncate_u128(#[out] res: *mut U128, #[frame] a: U128, to_bits: u64) {
        unsafe { *res = a.truncate(to_bits) };
    }

    #[opcode]
    fn truncate_f_to_u(#[out] res: *mut Field, #[frame] a: Field, to_bits: u64) {
        unsafe {
            let limb0 = ark_ff::PrimeField::into_bigint(a).0[0];
            let mask = if to_bits >= 64 {
                u64::MAX
            } else {
                (1u64 << to_bits) - 1
            };
            *res = From::from(limb0 & mask);
        }
    }

    #[opcode]
    fn add_field(#[out] res: *mut Field, #[frame] a: Field, #[frame] b: Field) {
        unsafe {
            *res = a + b;
        }
    }

    #[opcode]
    fn sub_field(#[out] res: *mut Field, #[frame] a: Field, #[frame] b: Field) {
        unsafe {
            *res = a - b;
        }
    }

    #[opcode]
    #[inline(never)]
    fn div_field(#[out] res: *mut Field, #[frame] a: Field, #[frame] b: Field) {
        unsafe {
            *res = if b == Field::ZERO { Field::ZERO } else { a / b };
        }
    }

    #[opcode]
    fn mul_field(#[out] res: *mut Field, #[frame] a: Field, #[frame] b: Field) {
        unsafe {
            *res = a * b;
        }
    }

    #[opcode]
    fn cast_field_to_u64(#[out] res: *mut u64, #[frame] a: Field) {
        unsafe {
            *res = ark_ff::PrimeField::into_bigint(a).0[0];
        }
    }

    #[opcode]
    fn cast_field_to_u128(#[out] res: *mut U128, #[frame] a: Field) {
        let limbs = ark_ff::PrimeField::into_bigint(a).0;
        unsafe {
            *res = U128 {
                lo: limbs[0],
                hi: limbs[1],
            }
        };
    }

    #[opcode]
    fn cast_u64_to_field(#[out] res: *mut Field, #[frame] a: u64) {
        unsafe {
            *res = From::from(a);
        }
    }

    #[opcode]
    fn cast_u128_to_field(#[out] res: *mut Field, #[frame] a: U128) {
        unsafe {
            *res = Field::from(a.to_u128());
        }
    }

    #[opcode]
    fn array_alloc(
        #[out] res: *mut BoxedValue,
        stride: usize,
        meta: BoxedLayout,
        items: &[FramePosition],
        frame: Frame,
        vm: &mut VM,
    ) {
        let array = BoxedValue::alloc(meta, vm);
        // println!(
        //     "array_alloc: size={} stride={} has_ptr_elems={} @ {:?}",
        //     meta.size(),
        //     stride,
        //     meta.ptr_elems(),
        //     array.0
        // );
        for (i, item) in items.iter().enumerate() {
            let tgt = array.array_idx(i, stride);
            unsafe {
                frame.write_to(tgt, item.0 as isize, stride);
            }
        }
        // println!(
        //     "array_alloc: array={:?} stride={} size={} storage_size={}",
        //     array.0,
        //     stride,
        //     array.layout().array_size(),
        //     array.layout().underlying_array_size()
        // );
        unsafe {
            *res = array;
        }
    }

    #[opcode]
    fn array_alloc_from_frame(
        #[out] res: *mut BoxedValue,
        stride: usize,
        meta: BoxedLayout,
        count: usize,
        source: FramePosition,
        frame: Frame,
        vm: &mut VM,
    ) {
        let array = BoxedValue::alloc(meta, vm);
        unsafe {
            frame.write_to(array.data(), source.0 as isize, count * stride);
            *res = array;
        }
    }

    #[opcode]
    fn array_alloc_repeated(
        #[out] res: *mut BoxedValue,
        stride: usize,
        meta: BoxedLayout,
        count: usize,
        item: FramePosition,
        frame: Frame,
        vm: &mut VM,
    ) {
        let array = BoxedValue::alloc(meta, vm);
        for i in 0..count {
            let tgt = array.array_idx(i, stride);
            unsafe {
                frame.write_to(tgt, item.0 as isize, stride);
            }
        }
        unsafe {
            *res = array;
        }
    }

    #[opcode]
    #[inline(never)]
    fn tuple_alloc(
        #[out] res: *mut BoxedValue,
        meta: BoxedLayout,
        fields: &[FramePosition],
        frame: Frame,
        vm: &mut VM,
    ) {
        let tuple = BoxedValue::alloc(meta, vm);
        let view = meta.as_struct(&vm.struct_layouts);
        let mut field_offset = 0;
        for (i, field) in fields.iter().enumerate() {
            let size = view.field_size(i);
            let tgt = unsafe { tuple.data().add(field_offset) };
            unsafe {
                frame.write_to(tgt, field.0 as isize, size);
            }
            field_offset += size;
        }
        unsafe {
            *res = tuple;
        }
    }

    #[opcode]
    fn ref_alloc(#[out] res: *mut BoxedValue, meta: BoxedLayout, vm: &mut VM) {
        let cell = BoxedValue::alloc(meta, vm);
        unsafe {
            ptr::write_bytes(cell.data(), 0, meta.ref_cell_elem_size());
            *res = cell;
        }
    }

    #[opcode]
    #[inline(never)]
    fn ref_store(
        #[frame] cell: BoxedValue,
        source: FramePosition,
        stride: usize,
        elem_rc: usize,
        frame: Frame,
        vm: &mut VM,
    ) {
        if elem_rc != 0 {
            let old = unsafe { *(cell.data() as *mut BoxedValue) };
            if !old.0.is_null() {
                old.dec_rc(vm);
            }
        }
        unsafe {
            frame.write_to(cell.data(), source.0 as isize, stride);
        }
    }

    #[opcode]
    fn ref_load(#[out] res: *mut u64, #[frame] cell: BoxedValue, stride: usize) {
        unsafe {
            ptr::copy_nonoverlapping(cell.data(), res, stride);
        }
    }

    #[opcode]
    fn array_get(
        #[out] res: *mut u64,
        #[frame] array: BoxedValue,
        #[frame] index: u64,
        stride: usize,
        vm: &mut VM,
    ) {
        assert!(
            (index as usize) * stride < array.layout().array_size(),
            "array_get: index {} out of bounds for array of length {}",
            index,
            array.layout().array_size() / stride
        );
        let src = array.array_idx(index as usize, stride);
        unsafe {
            ptr::copy_nonoverlapping(src, res, stride);
        }
    }

    /// Read an element out of a blob: a raw sequence of `len` elements of
    /// `stride` cells each, stored inline in the frame starting at `source`.
    #[opcode]
    fn blob_get(
        #[out] res: *mut u64,
        source: FramePosition,
        #[frame] index: u64,
        stride: usize,
        len: usize,
        frame: Frame,
    ) {
        assert!(
            (index as usize) < len,
            "blob_get: index {} out of bounds for blob of length {}",
            index,
            len
        );
        unsafe {
            frame.write_to(res, (source.0 + (index as usize) * stride) as isize, stride);
        }
    }

    #[opcode]
    fn tuple_proj(
        #[out] res: *mut u64,
        #[frame] tuple: BoxedValue,
        field_offset: usize,
        field_size: usize,
        vm: &mut VM,
    ) {
        let src = unsafe { tuple.data().add(field_offset) };
        unsafe {
            ptr::copy_nonoverlapping(src, res, field_size);
        }
    }

    #[opcode]
    #[inline(never)]
    fn array_set(
        #[out] res: *mut BoxedValue,
        #[frame] array: BoxedValue,
        #[frame] index: u64,
        source: FramePosition,
        stride: usize,
        frame: Frame,
        vm: &mut VM,
    ) {
        assert!(
            (index as usize) * stride < array.layout().array_size(),
            "array_set: index {} out of bounds for array of length {}",
            index,
            array.layout().array_size() / stride
        );
        let new_array = array.copy_if_reused(vm);
        let target = new_array.array_idx(index as usize, stride);
        if new_array.layout().data_type() == DataType::BoxedArray {
            if new_array.0 == array.0 {
                // if we're reusing the array, the old element needs to be garbage collected
                let old_elem = unsafe { *(target as *mut BoxedValue) };
                old_elem.dec_rc(vm);
            } else {
                // if we're not reusing the array, we need to bump RC of all _other_ elements,
                // because they're now aliased in the new array.
                for i in 0..new_array.layout().array_size() {
                    if i != index as usize {
                        let elem = unsafe { *(new_array.array_idx(i, stride) as *mut BoxedValue) };
                        elem.inc_rc(1);
                    }
                }
            }
        }
        unsafe {
            frame.write_to(target, source.0 as isize, stride);
            *res = new_array;
        }
    }

    #[opcode]
    fn slice_len(#[out] res: *mut u64, #[frame] array: BoxedValue, stride: usize) {
        let len = array.layout().array_size() / stride;
        unsafe {
            *res = len as u64;
        }
    }

    #[opcode]
    fn slice_push(
        #[out] res: *mut BoxedValue,
        #[frame] slice: BoxedValue,
        stride: usize,
        is_push_front: usize,
        values: &[FramePosition],
        frame: Frame,
        vm: &mut VM,
    ) {
        let extra_space_needed = values.len() * stride;
        let new_array = slice.alloc_grown_slice(extra_space_needed, is_push_front, vm);
        let pushed_data_offset = if is_push_front != 0 {
            0
        } else {
            new_array.layout().array_size() - extra_space_needed
        };
        for (i, item) in values.iter().enumerate() {
            let tgt = unsafe { new_array.data().add(pushed_data_offset + i * stride) };
            unsafe {
                frame.write_to(tgt, item.0 as isize, stride);
            }
        }
        unsafe {
            *res = new_array;
        }
    }

    #[opcode]
    fn inc_rc(#[frame] array: BoxedValue, amount: u64) {
        // println!("inc_array_rc_intro");
        array.inc_rc(amount);
        // println!("inc_array_rc_outro");
    }

    #[opcode]
    #[inline(never)]
    fn dec_rc(#[frame] array: BoxedValue, vm: &mut VM) {
        // println!("dec_array_rc_intro");
        array.dec_rc(vm);
        // println!("dec_array_rc_outro");
    }

    #[opcode]
    fn witness_ref_alloc(#[out] res: *mut BoxedValue, data: Field, vm: &mut VM) {
        let val = BoxedValue::alloc(BoxedLayout::ad_const(), vm);
        let d = val.as_ad_const();
        unsafe {
            (*d).value = data;
            *res = val;
        };
    }

    #[opcode]
    fn bump_da(#[frame] v: BoxedValue, #[frame] coeff: Field, vm: &mut VM) {
        v.bump_da(coeff, vm);
    }

    #[opcode]
    fn bump_db(#[frame] v: BoxedValue, #[frame] coeff: Field, vm: &mut VM) {
        v.bump_db(coeff, vm);
    }

    #[opcode]
    fn bump_dc(#[frame] v: BoxedValue, #[frame] coeff: Field, vm: &mut VM) {
        v.bump_dc(coeff, vm);
    }

    #[opcode]
    fn next_d_coeff(#[out] v: *mut Field, vm: &mut VM) {
        unsafe {
            *v = *vm.data.as_ad.ad_coeffs.add(vm.data.as_ad.current_cnst_off);
            vm.data.as_ad.current_cnst_off += 1;
        };
    }

    #[opcode]
    fn fresh_witness(#[out] res: *mut BoxedValue, vm: &mut VM) {
        let index = unsafe { vm.data.as_ad.current_wit_off as u64 };
        unsafe { vm.data.as_ad.current_wit_off += 1 };
        let val = BoxedValue::alloc(BoxedLayout::ad_witness(), vm);
        let d = val.as_ad_witness();
        unsafe {
            (*d).index = index;
            *res = val;
        }
    }

    #[opcode]
    fn pure_to_witness_ref(#[out] res: *mut BoxedValue, #[frame] v: Field, vm: &mut VM) {
        let val = BoxedValue::alloc(BoxedLayout::ad_const(), vm);
        let d = val.as_ad_const();
        unsafe {
            (*d).value = v;
            *res = val;
        }
    }

    #[opcode]
    fn unbox_field(#[out] res: *mut Field, #[frame] v: BoxedValue) {
        let d = v.as_ad_const();
        unsafe {
            *res = (*d).value;
        }
    }

    #[opcode]
    fn mul_const(
        #[out] res: *mut BoxedValue,
        #[frame] coeff: Field,
        #[frame] v: BoxedValue,
        vm: &mut VM,
    ) {
        let val = BoxedValue::alloc(BoxedLayout::mul_const(), vm);
        let d = val.as_mul_const();
        unsafe {
            (*d).coeff = coeff;
            (*d).value = v;
            (*d).da = Field::ZERO;
            (*d).db = Field::ZERO;
            (*d).dc = Field::ZERO;
            *res = val;
        }
    }

    #[opcode]
    fn add_boxed(
        #[out] res: *mut BoxedValue,
        #[frame] a: BoxedValue,
        #[frame] b: BoxedValue,
        vm: &mut VM,
    ) {
        let val = BoxedValue::alloc(BoxedLayout::ad_sum(), vm);
        let d = val.as_ad_sum();
        unsafe {
            (*d).a = a;
            (*d).b = b;
            (*d).da = Field::ZERO;
            (*d).db = Field::ZERO;
            (*d).dc = Field::ZERO;
            *res = val;
        }
    }

    #[raw_opcode]
    fn assert_eq_u64(
        pc: *const u64,
        frame: Frame,
        vm: &mut VM,
        #[frame] a: u64,
        #[frame] b: u64,
    ) -> (*const u64, Frame) {
        if a != b {
            return trap(pc, frame, vm);
        }
        (unsafe { pc.offset(3) }, frame)
    }

    #[raw_opcode]
    fn assert_eq_u128(
        pc: *const u64,
        frame: Frame,
        vm: &mut VM,
        #[frame] a: U128,
        #[frame] b: U128,
    ) -> (*const u64, Frame) {
        if a != b {
            return trap(pc, frame, vm);
        }
        (unsafe { pc.offset(3) }, frame)
    }

    #[raw_opcode]
    fn assert_eq_field(
        pc: *const u64,
        frame: Frame,
        vm: &mut VM,
        #[frame] a: Field,
        #[frame] b: Field,
    ) -> (*const u64, Frame) {
        if a != b {
            return trap(pc, frame, vm);
        }
        (unsafe { pc.offset(3) }, frame)
    }

    #[raw_opcode]
    fn assert_r1c(
        pc: *const u64,
        frame: Frame,
        vm: &mut VM,
        #[frame] a: Field,
        #[frame] b: Field,
        #[frame] c: Field,
    ) -> (*const u64, Frame) {
        if a * b != c {
            return trap(pc, frame, vm);
        }
        (unsafe { pc.offset(4) }, frame)
    }

    #[raw_opcode]
    #[inline(never)] // TODO better impl
    fn rangecheck(
        pc: *const u64,
        frame: Frame,
        vm: &mut VM,
        #[frame] val: Field,
        max_bits: usize,
    ) -> (*const u64, Frame) {
        // Convert field to bigint and check if it fits in max_bits
        let bigint = ark_ff::PrimeField::into_bigint(val);
        let check = bigint.to_bits_le().iter().skip(max_bits).all(|b| !b);
        if !check {
            return trap(pc, frame, vm);
        }
        (unsafe { pc.offset(3) }, frame)
    }

    #[opcode]
    fn to_bytes_be(#[frame] val: Field, count: u64, #[out] res: *mut BoxedValue, vm: &mut VM) {
        let val = ark_ff::PrimeField::into_bigint(val);
        let r = BoxedValue::alloc(BoxedLayout::array(count as usize, false), vm);
        unsafe {
            for i in 0..count {
                // Each limb in val.0 is a u64 (8 bytes), little-endian limb order
                let byte_idx = i as usize; // byte index from LSB
                let limb_idx = byte_idx / 8;
                let byte_in_limb = byte_idx % 8;
                let byte_val = if limb_idx < val.0.len() {
                    (val.0[limb_idx] >> (byte_in_limb * 8)) & 0xFF
                } else {
                    0
                };
                *r.array_idx((count - i - 1) as usize, 1) = byte_val;
            }
            *res = r;
        }
    }

    #[opcode]
    fn to_bytes_le(#[frame] val: Field, count: u64, #[out] res: *mut BoxedValue, vm: &mut VM) {
        let val = ark_ff::PrimeField::into_bigint(val);
        let r = BoxedValue::alloc(BoxedLayout::array(count as usize, false), vm);
        unsafe {
            for i in 0..count {
                // Each limb in val.0 is a u64 (8 bytes), little-endian limb order.
                let byte_idx = i as usize;
                let limb_idx = byte_idx / 8;
                let byte_in_limb = byte_idx % 8;
                let byte_val = if limb_idx < val.0.len() {
                    (val.0[limb_idx] >> (byte_in_limb * 8)) & 0xFF
                } else {
                    0
                };
                *r.array_idx(i as usize, 1) = byte_val;
            }
            *res = r;
        }
    }

    #[opcode]
    fn to_bits_le(#[out] res: *mut BoxedValue, #[frame] val: Field, count: u64, vm: &mut VM) {
        panic!("to_bits_be_lt_8 not implemented");
    }

    #[opcode]
    fn spread_u32(#[out] res: *mut u64, #[frame] val: u64) {
        let result = spread_bits(val as u32);
        unsafe {
            *res = result;
        }
    }

    #[opcode]
    fn unspread_u64(#[out] res_and: *mut u64, #[out] res_xor: *mut u64, #[frame] val: u64) {
        let (and_val, xor_val) = unspread_bits(val);
        unsafe {
            *res_and = and_val as u64;
            *res_xor = xor_val as u64;
        }
    }

    #[opcode]
    fn spread_lookup_field(
        #[frame] val: Field,
        #[frame] result: Field,
        #[frame] flag: Field,
        bits: usize,
        vm: &mut VM,
    ) {
        // Initialize spread table for this bit-width on first call.
        //
        // Spread tables use the folded single-constraint allocation
        // (`TableKind::Spread`): both operands of each entry (key=i,
        // value=spread(i)) are constants, so each entry is just one
        // `y·(α-i+β·spread(i))=m` constraint/witness instead of the generic
        // two-constraint key-value form. Phase 2 recomputes `spread(i)` itself,
        // so there is nothing to dump here.
        if vm.spread_tables[bits].is_none() {
            let length = 1usize << bits;
            let table_info = TableInfo {
                multiplicities_wit: unsafe { vm.data.as_forward.multiplicities_witness },
                num_indices: 1,
                kind: TableKind::Spread,
                length,
                elem_inverses_constraint_section_offset: unsafe {
                    vm.data.as_forward.elem_inverses_constraint_section_offset
                },
                elem_inverses_witness_section_offset: unsafe {
                    vm.data.as_forward.elem_inverses_witness_section_offset
                },
            };
            vm.spread_tables[bits] = Some(vm.tables.len());
            vm.tables.push(table_info);

            unsafe {
                vm.data.as_forward.multiplicities_witness =
                    vm.data.as_forward.multiplicities_witness.add(length);
                // One constraint per entry + one sum constraint; one witness per entry.
                vm.data.as_forward.elem_inverses_constraint_section_offset += length + 1;
                vm.data.as_forward.elem_inverses_witness_section_offset += length;
            }
        }

        let table_idx = vm.spread_tables[bits].unwrap();
        let flag_u64 = ark_ff::PrimeField::into_bigint(flag).0[0];
        unsafe { forward_kv_lookup_emit(table_idx, val, result, flag_u64, vm) };
    }

    #[opcode]
    fn dspread_lookup_field(
        #[frame] val: BoxedValue,
        #[frame] result: BoxedValue,
        #[frame] flag: BoxedValue,
        bits: usize,
        vm: &mut VM,
    ) {
        if vm.spread_tables[bits].is_none() {
            let length = 1usize << bits;
            let inverses_constraint_section_offset =
                unsafe { vm.data.as_ad.current_cnst_tables_off };
            let inverses_witness_section_offset = unsafe { vm.data.as_ad.current_wit_tables_off };
            let multiplicities_wit_offset = unsafe { vm.data.as_ad.current_wit_multiplicities_off };
            let table_info = TableInfo {
                multiplicities_wit: ptr::null_mut(),
                num_indices: 1,
                kind: TableKind::Spread,
                length,
                elem_inverses_witness_section_offset: inverses_witness_section_offset,
                elem_inverses_constraint_section_offset: inverses_constraint_section_offset,
            };
            vm.spread_tables[bits] = Some(vm.tables.len());
            vm.tables.push(table_info);
            unsafe {
                // Folded allocation: one constraint per entry + one sum
                // constraint; one witness per entry.
                vm.data.as_ad.current_wit_multiplicities_off += length;
                vm.data.as_ad.current_wit_tables_off += length;
                vm.data.as_ad.current_cnst_tables_off += length + 1;
            }

            let inv_sum_coeff = unsafe {
                *vm.data
                    .as_ad
                    .ad_coeffs
                    .offset(inverses_constraint_section_offset as isize + length as isize)
            };

            for i in 0..length {
                // Single folded constraint: y · (α - i + β·spread(i)) - m = 0
                //   A = (y), B = (α) + (w0, -i) + (β, spread(i)), C = (m)
                let coeff = unsafe {
                    *vm.data
                        .as_ad
                        .ad_coeffs
                        .offset(inverses_constraint_section_offset as isize + i as isize)
                };
                unsafe {
                    // da[y_wit] += coeff
                    *vm.data
                        .as_ad
                        .out_da
                        .offset(inverses_witness_section_offset as isize + i as isize) += coeff;

                    // db[α] += coeff
                    *vm.data
                        .as_ad
                        .out_db
                        .add(vm.data.as_ad.logup_wit_challenge_off) += coeff;
                    // db[w0] -= coeff * i
                    *vm.data.as_ad.out_db -= coeff * Field::from(i as u64);
                    // db[β] += coeff * spread(i)
                    *vm.data
                        .as_ad
                        .out_db
                        .offset(vm.data.as_ad.logup_wit_challenge_off as isize + 1) +=
                        coeff * Field::from(spread_bits(i as u32));

                    // dc[m] += coeff
                    *vm.data
                        .as_ad
                        .out_dc
                        .offset(multiplicities_wit_offset as isize + i as isize) += coeff;

                    // Sum: inv goes into A position
                    *vm.data
                        .as_ad
                        .out_da
                        .offset(inverses_witness_section_offset as isize + i as isize) +=
                        inv_sum_coeff;
                }
            }

            unsafe {
                *vm.data.as_ad.out_db += inv_sum_coeff;
            }
        }

        let table_idx = vm.spread_tables[bits].unwrap();
        unsafe { ad_kv_lookup_emit(table_idx, val, result, flag, vm) };
    }

    #[opcode]
    fn rngchk_field(#[frame] val: Field, #[frame] flag: Field, bits: usize, vm: &mut VM) {
        if vm.rgchk_tables[bits].is_none() {
            let length = 1usize << bits;
            let table_info = TableInfo {
                multiplicities_wit: unsafe { vm.data.as_forward.multiplicities_witness },
                num_indices: 1,
                kind: TableKind::RangeCheck,
                length,
                elem_inverses_constraint_section_offset: unsafe {
                    vm.data.as_forward.elem_inverses_constraint_section_offset
                },
                elem_inverses_witness_section_offset: unsafe {
                    vm.data.as_forward.elem_inverses_witness_section_offset
                },
            };
            vm.rgchk_tables[bits] = Some(vm.tables.len());
            vm.tables.push(table_info);
            unsafe {
                vm.data.as_forward.multiplicities_witness =
                    vm.data.as_forward.multiplicities_witness.add(length);
                vm.data.as_forward.elem_inverses_constraint_section_offset += length + 1;
                vm.data.as_forward.elem_inverses_witness_section_offset += length;
            }
        }
        let flag_u64 = ark_ff::PrimeField::into_bigint(flag).0[0];
        let table_idx = vm.rgchk_tables[bits].unwrap();
        let table_info = &vm.tables[table_idx];
        unsafe {
            if flag_u64 != 0 {
                let val_u64 = ark_ff::PrimeField::into_bigint(val).0[0];
                let ptr = table_info.multiplicities_wit.offset(val_u64 as isize);
                *(ptr as *mut u64) += flag_u64;
                *(vm.data.as_forward.lookups_a as *mut u64) = table_idx as u64;
                vm.data.as_forward.lookups_a = vm.data.as_forward.lookups_a.offset(1);
                *(vm.data.as_forward.lookups_b as *mut u64) = val_u64;
                vm.data.as_forward.lookups_b = vm.data.as_forward.lookups_b.offset(1);
            } else {
                *(vm.data.as_forward.lookups_a as *mut u64) = table_idx as u64;
                vm.data.as_forward.lookups_a = vm.data.as_forward.lookups_a.offset(1);
                *(vm.data.as_forward.lookups_b as *mut Field) = val;
                vm.data.as_forward.lookups_b = vm.data.as_forward.lookups_b.offset(1);
            }
            *(vm.data.as_forward.lookups_c as *mut u64) = flag_u64;
            vm.data.as_forward.lookups_c = vm.data.as_forward.lookups_c.offset(1);
        }
    }

    #[opcode]
    fn array_lookup_field(
        #[frame] array: BoxedValue,
        #[frame] index: Field,
        #[frame] result: Field,
        #[frame] flag: Field,
        stride: usize,
        elem_kind: usize,
        vm: &mut VM,
    ) {
        let table_id_ptr = array.table_id();
        let table_idx = unsafe { *table_id_ptr };

        let table_idx = if table_idx == u64::MAX {
            // First lookup on this array: create a new table
            let (cnst_off, wit_off, mult_wit) = unsafe {
                (
                    vm.data.as_forward.elem_inverses_constraint_section_offset,
                    vm.data.as_forward.elem_inverses_witness_section_offset,
                    vm.data.as_forward.multiplicities_witness,
                )
            };

            // Dump array element values into the x-slots (even offsets) of the table section
            let length = unsafe {
                for_each_array_leaf(array, stride, |i, elem_ptr| {
                    let elem_field = read_pure_elem_as_field(elem_ptr, elem_kind);
                    // Write it into the x-slot (even offset: 2*i) of the constraint section
                    *vm.data.as_forward.out_a_base.add(cnst_off + 2 * i) = elem_field;
                })
            };

            let table_info = TableInfo {
                multiplicities_wit: mult_wit,
                num_indices: 1,
                kind: TableKind::Array,
                length,
                elem_inverses_constraint_section_offset: cnst_off,
                elem_inverses_witness_section_offset: wit_off,
            };
            let new_table_idx = vm.tables.len();
            vm.tables.push(table_info);

            unsafe {
                vm.data.as_forward.multiplicities_witness = mult_wit.add(length);
                // 2 constraints per element + 1 sum constraint
                vm.data.as_forward.elem_inverses_constraint_section_offset += 2 * length + 1;
                // 2 witness slots per element
                vm.data.as_forward.elem_inverses_witness_section_offset += 2 * length;
            }

            // Store table index on the array
            unsafe { *table_id_ptr = new_table_idx as u64 };

            new_table_idx
        } else {
            table_idx as usize
        };

        let flag_u64 = ark_ff::PrimeField::into_bigint(flag).0[0];
        unsafe { forward_kv_lookup_emit(table_idx, index, result, flag_u64, vm) };
    }

    #[opcode]
    fn drngchk_field(
        #[frame] val: BoxedValue,
        #[frame] flag: BoxedValue,
        bits: usize,
        vm: &mut VM,
    ) {
        let length = 1usize << bits;
        if vm.rgchk_tables[bits].is_none() {
            let inverses_constraint_section_offset =
                unsafe { vm.data.as_ad.current_cnst_tables_off };
            let inverses_witness_section_offset = unsafe { vm.data.as_ad.current_wit_tables_off };
            let multiplicities_wit_offset = unsafe { vm.data.as_ad.current_wit_multiplicities_off };
            let table_info = TableInfo {
                multiplicities_wit: ptr::null_mut(),
                num_indices: 1,
                kind: TableKind::RangeCheck,
                length,
                elem_inverses_witness_section_offset: inverses_witness_section_offset,
                elem_inverses_constraint_section_offset: inverses_constraint_section_offset,
            };
            vm.rgchk_tables[bits] = Some(vm.tables.len());
            vm.tables.push(table_info);
            unsafe {
                vm.data.as_ad.current_wit_multiplicities_off += length;
                vm.data.as_ad.current_wit_tables_off += length;
                vm.data.as_ad.current_cnst_tables_off += length + 1;
            }
            let inv_sum_coeff = unsafe {
                *vm.data
                    .as_ad
                    .ad_coeffs
                    .offset(inverses_constraint_section_offset as isize + length as isize)
            };

            for i in 0..length as isize {
                // For each element in the table, we have constraint `elem_inv_witness * (alpha - i) - multiplicity_witness = 0`
                let coeff = unsafe {
                    *vm.data
                        .as_ad
                        .ad_coeffs
                        .offset(inverses_constraint_section_offset as isize + i)
                };
                unsafe {
                    *vm.data
                        .as_ad
                        .out_da
                        .offset(inverses_witness_section_offset as isize + i) += coeff;
                    // if i == 0 {
                    //     println!("bump da at {} from inv by {coeff}", inverses_witness_section_offset as isize + i);
                    // }

                    *vm.data
                        .as_ad
                        .out_db
                        .add(vm.data.as_ad.logup_wit_challenge_off) += coeff;
                    *vm.data.as_ad.out_db -= coeff * Field::from(i as u64);

                    *vm.data
                        .as_ad
                        .out_dc
                        .offset(multiplicities_wit_offset as isize + i) += coeff;
                }

                // Also each inv goes into the A position of the total sum
                unsafe {
                    *vm.data
                        .as_ad
                        .out_da
                        .offset(inverses_witness_section_offset as isize + i) += inv_sum_coeff;
                }
            }

            // The coeff at B on the sum constraint is just `1` so we bump it.
            unsafe {
                *vm.data.as_ad.out_db += inv_sum_coeff;
            }
        }
        let table_idx = vm.rgchk_tables[bits].unwrap();
        let table_info = &vm.tables[table_idx];

        let inv_coeff = unsafe {
            let r = *vm
                .data
                .as_ad
                .ad_coeffs
                .add(vm.data.as_ad.current_cnst_lookups_off);
            vm.data.as_ad.current_cnst_lookups_off += 1;
            r
        };

        let inv_sum_coeff = unsafe {
            *vm.data
                .as_ad
                .ad_coeffs
                .add(table_info.elem_inverses_constraint_section_offset + length)
        };

        let current_inv_wit_offset = unsafe {
            let r = vm.data.as_ad.current_wit_lookups_off;
            vm.data.as_ad.current_wit_lookups_off += 1;
            r
        };

        unsafe {
            // bump for the RHS of the sum
            *vm.data.as_ad.out_dc.add(current_inv_wit_offset) += inv_sum_coeff;

            // bumps for the inversion assert: y*(α-key) = flag
            // da[y] += inv_coeff
            *vm.data.as_ad.out_da.add(current_inv_wit_offset) += inv_coeff;

            // db[α] += inv_coeff
            *vm.data
                .as_ad
                .out_db
                .add(vm.data.as_ad.logup_wit_challenge_off) += inv_coeff;
            // db[key] -= inv_coeff
            val.bump_db(-inv_coeff, vm);

            // dc[flag] += inv_coeff  (RHS is flag, not constant 1)
            flag.bump_dc(inv_coeff, vm);
        }
    }

    #[opcode]
    fn darray_lookup_field(
        #[frame] array: BoxedValue,
        #[frame] index: BoxedValue,
        #[frame] result: BoxedValue,
        #[frame] flag: BoxedValue,
        stride: usize,
        elem_kind: usize,
        vm: &mut VM,
    ) {
        let table_id_ptr = array.table_id();
        let table_idx = unsafe { *table_id_ptr };

        let table_idx = if table_idx == u64::MAX {
            // First AD call on this array: create table and process table constraints
            let inverses_constraint_section_offset =
                unsafe { vm.data.as_ad.current_cnst_tables_off };
            let inverses_witness_section_offset = unsafe { vm.data.as_ad.current_wit_tables_off };
            let multiplicities_wit_offset = unsafe { vm.data.as_ad.current_wit_multiplicities_off };

            let length =
                unsafe {
                    for_each_array_leaf(array, stride, |i, elem_ptr| {
                        // x-constraint at base + 2*i: A=[(beta,1)], B=v_i, C=[(x,-1)]
                        let x_coeff =
                            *vm.data.as_ad.ad_coeffs.offset(
                                inverses_constraint_section_offset as isize + 2 * i as isize,
                            );
                        // da[beta] += x_coeff (A entry: (beta, 1))
                        *vm.data
                            .as_ad
                            .out_da
                            .offset(vm.data.as_ad.logup_wit_challenge_off as isize + 1) += x_coeff;
                        // db[v_i] += x_coeff (B entry: element value)
                        lookup_elem_bump_db(elem_ptr, elem_kind, x_coeff, vm);
                        // dc[x_wit] -= x_coeff (C entry: (x, -1))
                        *vm.data
                            .as_ad
                            .out_dc
                            .offset(inverses_witness_section_offset as isize + 2 * i as isize) -=
                            x_coeff;

                        // y-constraint at base + 2*i + 1: A=y_i, B=(alpha - i - x_i), C=mult_i
                        let y_coeff = *vm.data.as_ad.ad_coeffs.offset(
                            inverses_constraint_section_offset as isize + 2 * i as isize + 1,
                        );
                        // dA[y_witness] += y_coeff
                        *vm.data.as_ad.out_da.offset(
                            inverses_witness_section_offset as isize + 2 * i as isize + 1,
                        ) += y_coeff;
                        // dB[alpha] += y_coeff
                        *vm.data
                            .as_ad
                            .out_db
                            .add(vm.data.as_ad.logup_wit_challenge_off) += y_coeff;
                        // dB -= y_coeff * i (constant part)
                        *vm.data.as_ad.out_db -= y_coeff * Field::from(i as u64);
                        // dB[x_witness] -= y_coeff (x_i appears negated in B)
                        *vm.data
                            .as_ad
                            .out_db
                            .add(inverses_witness_section_offset + 2 * i) -= y_coeff;
                        // dC[mult_witness] += y_coeff
                        *vm.data.as_ad.out_dc.add(multiplicities_wit_offset + i) += y_coeff;
                    })
                };

            let sum_coeff = unsafe {
                *vm.data
                    .as_ad
                    .ad_coeffs
                    .offset(inverses_constraint_section_offset as isize + 2 * length as isize)
            };

            // Sum constraint: y_i goes into A position
            for i in 0..length {
                unsafe {
                    *vm.data
                        .as_ad
                        .out_da
                        .add(inverses_witness_section_offset + 2 * i + 1) += sum_coeff;
                }
            }

            // Sum constraint B=1: bump out_db by sum_coeff
            unsafe {
                *vm.data.as_ad.out_db += sum_coeff;
            }

            let table_info = TableInfo {
                multiplicities_wit: ptr::null_mut(),
                num_indices: 1,
                kind: TableKind::Array,
                length,
                elem_inverses_witness_section_offset: inverses_witness_section_offset,
                elem_inverses_constraint_section_offset: inverses_constraint_section_offset,
            };
            let new_table_idx = vm.tables.len();
            vm.tables.push(table_info);
            unsafe {
                vm.data.as_ad.current_wit_multiplicities_off += length;
                vm.data.as_ad.current_wit_tables_off += 2 * length;
                vm.data.as_ad.current_cnst_tables_off += 2 * length + 1;
            }

            unsafe { *table_id_ptr = new_table_idx as u64 };
            new_table_idx
        } else {
            table_idx as usize
        };

        unsafe { ad_kv_lookup_emit(table_idx, index, result, flag, vm) };
    }

    #[opcode]
    fn init_global(
        vm: &mut VM,
        frame: Frame,
        src: FramePosition,
        global_offset: usize,
        size: usize,
    ) {
        unsafe {
            std::ptr::copy_nonoverlapping(
                frame.data.add(src.0),
                vm.globals.add(global_offset),
                size,
            );
        }
    }

    #[opcode]
    fn read_global(#[out] res: *mut u64, vm: &mut VM, global_offset: usize, size: usize) {
        unsafe {
            std::ptr::copy_nonoverlapping(vm.globals.add(global_offset), res, size);
        }
    }

    #[opcode]
    #[inline(never)]
    fn drop_global(vm: &mut VM, global_offset: usize) {
        unsafe {
            let boxed = *(vm.globals.add(global_offset) as *mut BoxedValue);
            boxed.dec_rc(vm);
        }
    }

    #[opcode]
    fn mov_const_pool(#[out] res: *mut u64, vm: &mut VM, pool_offset: usize, size: usize) {
        unsafe {
            std::ptr::copy_nonoverlapping(vm.constants.as_ptr().add(pool_offset), res, size);
        }
    }
}

pub struct Function {
    pub name: String,
    pub frame_size: usize,
    pub code: Vec<OpCode>,
    /// One location per opcode in `code`.
    pub source_locations: Vec<SourceLocation>,
}

impl Display for Function {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, "fn {} (frame_size = {}):", self.name, self.frame_size)?;
        for op in &self.code {
            writeln!(f, "  {}", op)?;
        }
        Ok(())
    }
}

/// Index of the witness-generation entry point in a program's entry table.
pub const ENTRY_WITGEN: usize = 0;
/// Index of the AD entry point in a program's entry table.
pub const ENTRY_AD: usize = 1;

pub struct Program {
    pub functions: Vec<Function>,
    /// Indices into `functions` of the program's entry points, in entry-table order
    /// ([`ENTRY_WITGEN`], [`ENTRY_AD`], ...).
    pub entry_points: Vec<usize>,
    pub global_frame_size: usize,
    pub struct_layouts: Vec<StructDescriptor>,
    /// Interned constant pool: a flat word buffer holding each distinct multi-cell constant
    /// once. Referenced by `MovConstPool { pool_offset, size }` instead of being re-spilled
    /// into every function's frame.
    pub constant_pool: Vec<u64>,
}

impl Display for Program {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let max_line_number: usize = self.functions.iter().map(|f| f.code.len()).sum::<usize>() - 1;
        let max_line_number_digits = max_line_number.to_string().len();
        let max_function_idx = self.functions.len().to_string().len() - 1;
        let max_function_idx_digits = max_function_idx.to_string().len();
        let mut line = 0;
        for (i, function) in self.functions.iter().enumerate() {
            writeln!(
                f,
                "{: >max_function_idx_digits$}: fn {} (frame_size = {})",
                i, function.name, function.frame_size
            )?;
            for op in &function.code {
                writeln!(f, "  {: >max_line_number_digits$}: {}", line, op)?;
                line += 1;
            }
        }
        Ok(())
    }
}

/// Encode a single field of a `StructDescriptor` as one `u64`:
/// high bit = refcounted flag, low 32 bits = field size in u64 words.
#[inline(always)]
fn encode_struct_field(size: u32, refcounted: bool) -> u64 {
    (refcounted as u64) << 63 | (size as u64)
}

#[inline(always)]
fn decode_struct_field(word: u64) -> (u32, bool) {
    let refcounted = (word >> 63) != 0;
    let size = (word & 0xFFFF_FFFF) as u32;
    (size, refcounted)
}

const DEBUG_INFO_MAGIC: u64 = u64::from_le_bytes(*b"MAVROSDB");

fn decode_string(program: &[u64], offset: &mut usize) -> String {
    let byte_len = program[*offset] as usize;
    *offset += 1;
    let word_len = byte_len.div_ceil(8);
    let mut bytes = Vec::with_capacity(word_len * 8);
    for word in &program[*offset..*offset + word_len] {
        bytes.extend_from_slice(&word.to_le_bytes());
    }
    *offset += word_len;
    bytes.truncate(byte_len);
    String::from_utf8(bytes).expect("source-map strings must be UTF-8")
}

impl Program {
    /// Serialize executable VM bytecode. Debug information is never embedded in this output.
    pub fn to_binary(&self) -> Vec<u64> {
        self.to_binary_and_debug_info().0
    }

    /// Backwards-compatible alias for [`Program::to_binary`].
    pub fn to_binary_without_debug_info(&self) -> Vec<u64> {
        self.to_binary()
    }

    /// Serialize compact executable bytecode and construct its standalone source map.
    pub fn to_binary_and_debug_info(&self) -> (Vec<u64>, DebugInfo) {
        let mut binary = Vec::new();
        // Layout-table header: [num_descriptors, ...descriptors...].
        // Each descriptor: [num_fields, field_0_packed, field_1_packed, ...].
        binary.push(self.struct_layouts.len() as u64);
        for desc in &self.struct_layouts {
            let fields = desc.fields();
            binary.push(fields.len() as u64);
            for &(size, refcounted) in fields {
                binary.push(encode_struct_field(size, refcounted));
            }
        }

        // Constant pool: [pool_len, ...words...].
        binary.push(self.constant_pool.len() as u64);
        binary.extend_from_slice(&self.constant_pool);

        binary.push(self.global_frame_size as u64);

        // Entry-point table: [num_entries, marker_offset_0, ...]. The offsets are absolute word
        // indices of each entry function's `u64::MAX` marker; they are patched in once function
        // positions are known.
        binary.push(self.entry_points.len() as u64);
        let entry_table_start = binary.len();
        binary.extend(std::iter::repeat(0u64).take(self.entry_points.len()));

        let mut positions = vec![];
        let mut jumps_to_fix: Vec<(usize, isize)> = vec![];
        let mut function_markers = vec![];
        let mut debug_functions = Vec::with_capacity(self.functions.len());

        for function in &self.functions {
            assert_eq!(
                function.code.len(),
                function.source_locations.len(),
                "every VM opcode must have a source location"
            );
            // Function marker
            function_markers.push(binary.len());
            let function_offset = binary.len();
            binary.push(u64::MAX);
            binary.push(function.frame_size as u64);

            let mut locations = Vec::new();
            for (opcode_index, op) in function.code.iter().enumerate() {
                let location = &function.source_locations[opcode_index];
                if opcode_index == 0 || function.source_locations[opcode_index - 1] != *location {
                    locations.push(DebugLocation {
                        code_offset: binary.len(),
                        location: location.clone(),
                    });
                }
                positions.push(binary.len());
                op.to_binary(&mut binary, &mut jumps_to_fix);
            }
            debug_functions.push(DebugFunction {
                name: function.name.clone(),
                code_offset: function_offset,
                locations,
            });
        }

        for (slot, fn_idx) in self.entry_points.iter().enumerate() {
            binary[entry_table_start + slot] = function_markers[*fn_idx] as u64;
        }
        for (jump_position, add_offset) in jumps_to_fix {
            let target = binary[jump_position];
            let target_pos = positions[target as usize];
            binary[jump_position] =
                (target_pos as isize - (jump_position as isize + add_offset)) as u64;
        }
        (
            binary,
            DebugInfo {
                format_version: 1,
                functions: debug_functions,
            },
        )
    }
}

/// The decoded header of a program binary.
pub struct ProgramHeader {
    pub struct_layouts: Vec<StructDescriptor>,
    /// Interned constant pool (flat words), read at runtime by `mov_const_pool`.
    pub constant_pool: Vec<u64>,
    pub global_frame_size: usize,
    /// Absolute word offsets of each entry point's function marker, in entry-table order
    /// ([`ENTRY_WITGEN`], [`ENTRY_AD`], ...). The entry's frame size lives at `offset + 1` and
    /// its first opcode at `offset + 2`.
    pub entry_points: Vec<usize>,
    pub debug_info: DebugInfo,
    /// Word offset of the first function marker, i.e. where the opcode stream begins.
    pub code_start: usize,
}

/// Decode a program binary's header: struct layouts, global frame size and the entry-point
/// table.
pub fn parse_program_header(program: &[u64]) -> ProgramHeader {
    let (struct_layouts, off) = parse_struct_layouts(program);
    let pool_len = program[off] as usize;
    let constant_pool = program[off + 1..off + 1 + pool_len].to_vec();
    let off = off + 1 + pool_len;
    let global_frame_size = program[off] as usize;
    let num_entries = program[off + 1] as usize;
    let entry_points: Vec<usize> = (0..num_entries)
        .map(|i| program[off + 2 + i] as usize)
        .collect();
    let mut code_start = off + 2 + num_entries;
    let debug_info = if program.get(code_start) == Some(&DEBUG_INFO_MAGIC) {
        code_start += 1;
        let num_files = program[code_start] as usize;
        code_start += 1;
        let files: Vec<String> = (0..num_files)
            .map(|_| decode_string(program, &mut code_start))
            .collect();
        let num_functions = program[code_start] as usize;
        code_start += 1;
        let mut functions = Vec::with_capacity(num_functions);
        for _ in 0..num_functions {
            let name = decode_string(program, &mut code_start);
            let function_offset = program[code_start] as usize;
            let num_locations = program[code_start + 1] as usize;
            code_start += 2;
            let mut locations = Vec::with_capacity(num_locations);
            for _ in 0..num_locations {
                let location_offset = program[code_start] as usize;
                let file_index = program[code_start + 1] as usize;
                let line = program[code_start + 2];
                let column = program[code_start + 3];
                code_start += 4;
                locations.push(DebugLocation {
                    code_offset: location_offset,
                    location: SourceLocation::new(files[file_index].clone(), line, column),
                });
            }
            functions.push(DebugFunction {
                name,
                code_offset: function_offset,
                locations,
            });
        }
        DebugInfo {
            format_version: 1,
            functions,
        }
    } else {
        DebugInfo::default()
    };
    ProgramHeader {
        struct_layouts,
        constant_pool,
        global_frame_size,
        entry_points,
        debug_info,
        code_start,
    }
}

/// Read the struct-layout table from the binary header and return both the
/// descriptors and the offset (in u64 words) at which the rest of the program
/// (starting with `global_frame_size`) begins.
pub fn parse_struct_layouts(program: &[u64]) -> (Vec<StructDescriptor>, usize) {
    let num_descriptors = program[0] as usize;
    let mut layouts = Vec::with_capacity(num_descriptors);
    let mut off = 1usize;
    for _ in 0..num_descriptors {
        let n = program[off] as usize;
        off += 1;
        let mut fields = Vec::with_capacity(n);
        for _ in 0..n {
            fields.push(decode_struct_field(program[off]));
            off += 1;
        }
        layouts.push(StructDescriptor::new(fields));
    }
    (layouts, off)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn location(function: &str, line: u64) -> SourceLocation {
        SourceLocation::new(format!("src/{function}.nr"), line, 7)
    }

    #[test]
    fn source_map_drives_trap_stack_trace() {
        let caller_location = location("main", 10);
        let callee_location = location("helper", 24);
        let program = Program {
            functions: vec![
                Function {
                    name: "main".to_string(),
                    frame_size: 3,
                    code: vec![OpCode::Nop {}, OpCode::Ret {}],
                    source_locations: vec![caller_location.clone(), caller_location.clone()],
                },
                Function {
                    name: "helper".to_string(),
                    frame_size: 3,
                    code: vec![OpCode::Nop {}, OpCode::Ret {}],
                    source_locations: vec![callee_location.clone(), callee_location.clone()],
                },
            ],
            entry_points: vec![0],
            global_frame_size: 0,
            struct_layouts: Vec::new(),
            constant_pool: Vec::new(),
        };
        let (binary, debug_info) = program.to_binary_and_debug_info();
        let main_opcode = debug_info.functions[0].locations[0].code_offset;
        let helper_opcode = debug_info.functions[1].locations[0].code_offset;

        let mut vm = VM::new_witgen(
            ptr::null_mut(),
            ptr::null_mut(),
            ptr::null_mut(),
            ptr::null_mut(),
            ptr::null_mut(),
            ptr::null_mut(),
            ptr::null_mut(),
            ptr::null_mut(),
            0,
            0,
            ptr::null_mut(),
            Vec::new(),
            Vec::new(),
        );
        vm.set_debug_context(binary.as_ptr(), binary.len(), debug_info);

        let caller = Frame::base_frame(3, &mut vm);
        let callee = Frame::push(3, caller, &mut vm);
        unsafe {
            *callee.data.offset(1) = binary.as_ptr().add(main_opcode + 1) as u64;
        }
        vm.capture_trap(unsafe { binary.as_ptr().add(helper_opcode) }, callee);

        assert_eq!(
            vm.stack_trace,
            vec![
                StackFrame {
                    function: "helper".to_string(),
                    location: callee_location,
                },
                StackFrame {
                    function: "main".to_string(),
                    location: caller_location,
                },
            ]
        );

        let caller = callee.pop(&mut vm);
        let root = caller.pop(&mut vm);
        assert!(root.data.is_null());
    }

    #[test]
    fn binaries_without_debug_header_still_parse() {
        // Empty header: no struct layouts, constants, globals, or entries, then code starts.
        let binary = [0, 0, 0, 0, u64::MAX, 0];
        let header = parse_program_header(&binary);

        assert_eq!(header.code_start, 4);
        assert!(header.constant_pool.is_empty());
        assert!(header.debug_info.functions.is_empty());
    }

    #[test]
    fn bytecode_debug_info_is_always_standalone() {
        let source_location = location("main", 10);
        let program = Program {
            functions: vec![Function {
                name: "main".to_string(),
                frame_size: 3,
                code: vec![OpCode::Nop {}, OpCode::Ret {}],
                source_locations: vec![source_location.clone(), source_location],
            }],
            entry_points: vec![0],
            global_frame_size: 0,
            struct_layouts: Vec::new(),
            constant_pool: Vec::new(),
        };

        let (binary, debug_info) = program.to_binary_and_debug_info();

        assert_eq!(binary, program.to_binary_without_debug_info());
        assert_eq!(binary, program.to_binary());
        assert!(
            parse_program_header(&binary)
                .debug_info
                .functions
                .is_empty()
        );
        assert_eq!(debug_info.format_version, 1);
        assert_eq!(debug_info.functions.len(), 1);
        assert_eq!(debug_info.functions[0].name, "main");
        assert_eq!(debug_info.functions[0].locations.len(), 1);
        assert_eq!(parse_program_header(&binary).entry_points.len(), 1);
    }
}
