[package]
name = "passport_08_complete_age_check"
type = "bin"
authors = [""]

[dependencies]
compare_age = { path = "../../noir-passport-monolithic/utils/compare/age" }
data_check_expiry = { path = "../../noir-passport-monolithic/utils/data-check/expiry" }
passport_validity_check = { path = "../../noir-passport-monolithic/utils/passport_validity_check" }
