[package]
name = "mavros_ecdsa"
type = "lib"
authors = ["Reilabs"]
compiler_version = ">=1.0.0"

[dependencies]
ecdsa = { tag = "v0.4.0", git = "https://github.com/zkpassport/noir-ecdsa" }
bignum = { tag = "v0.10.0-1", git = "https://github.com/zkpassport/noir-bignum" }
